### PR TITLE
Adding saving feature

### PR DESCRIPTION
**Pull request by Voidsay**
Alrighty, let's see if it works how I expected. Sorry, it is my first time using github to merge, expect issues.

### CODE REVIEW

**Comment by piso101** [comment]
no woriess man! its pretty complicated. thanks for your efford tho !!

**Comment by Voidsay** [comment]
@piso101 you can @ me you still have a question, just know that I am rarely on github, so a reply can take a while.

**Comment by piso101** [comment]
@Voidsay still doesnt work i dont know what is wrong hub doesnt seem to find prefabs cuz phone vibrates when scene changes

**Comment by Voidsay** [comment]
@piso101 does it work in the editor? The thing is really hacky and I've only set it up to work for a single scene and a single bed.

**Pull request merged**
